using JobTracker.Core.Enums;

namespace JobTracker.Core.Models
{
    public class Job
    {
        public int Id { get; set; }

        // This is the "R000001" style job number — generated by our service later
        public required string JobNo { get; set; }

        // We store the enum value (Repair/Support/Warranty)
        public JobType JobType { get; set; }

        // DateTime stores both date AND time. We only care about the date,
        // but DateTime is the standard type used in C# for this.
        public DateTime Date { get; set; }

        // "ClientId" is a Foreign Key — it links this job to a specific client.
        // Think of it like the client's "ID card number" written on the job form.
        public int ClientId { get; set; }

        // Navigation property — lets us access the full Client object from a Job.
        // The "?" means it might not always be loaded (it's optional/lazy).
        public Client? Client { get; set; }

        // One job can have many time cards
        public ICollection<TimeCard> TimeCards { get; set; } = new List<TimeCard>();
    }
}