// <auto-generated />
using System;
using JobTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413202446_AddWarrantyJobSeed")]
    partial class AddWarrantyJobSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobTracker.Core.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Acme Corp",
                            ContactName = "John Smith",
                            PhoneNumber = "0112345678"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "TechSolve",
                            ContactName = "Sarah Jones",
                            PhoneNumber = "0219876543"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Deloitte",
                            ContactName = "Melanie Scott",
                            PhoneNumber = "0209846573"
                        });
                });

            modelBuilder.Entity("JobTracker.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeCode = "EMP001",
                            FullName = "Mike Johnson"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeCode = "EMP002",
                            FullName = "Lisa Brown"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeCode = "EMP003",
                            FullName = "Robin McGee"
                        });
                });

            modelBuilder.Entity("JobTracker.Core.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobNo = "R000001",
                            JobType = 0
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            Date = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobNo = "S000001",
                            JobType = 1
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            Date = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobNo = "W000001",
                            JobType = 2
                        });
                });

            modelBuilder.Entity("JobTracker.Core.Models.TimeCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateWorked")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JobId");

                    b.ToTable("TimeCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateWorked = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            HoursWorked = 4.5m,
                            JobId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateWorked = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            HoursWorked = 3.0m,
                            JobId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateWorked = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            HoursWorked = 6.0m,
                            JobId = 3
                        });
                });

            modelBuilder.Entity("JobTracker.Core.Models.Job", b =>
                {
                    b.HasOne("JobTracker.Core.Models.Client", "Client")
                        .WithMany("Jobs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("JobTracker.Core.Models.TimeCard", b =>
                {
                    b.HasOne("JobTracker.Core.Models.Employee", "Employee")
                        .WithMany("TimeCards")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobTracker.Core.Models.Job", "Job")
                        .WithMany("TimeCards")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobTracker.Core.Models.Client", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobTracker.Core.Models.Employee", b =>
                {
                    b.Navigation("TimeCards");
                });

            modelBuilder.Entity("JobTracker.Core.Models.Job", b =>
                {
                    b.Navigation("TimeCards");
                });
#pragma warning restore 612, 618
        }
    }
}
